#ifndef _INCLUDED_PTEST_H_
#define _INCLUDED_PTEST_H_

/* This File was automatically generated by the CEncoder. Do not modify it!
Date: Wed Feb 15 17:26:44 2017 
File: ptest.htm */

#define PTEST_FILE_LEN	286

extern const unsigned char ptest_file [];

#endif

